# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "puppetlabs/ubuntu-14.04-64-nocm"

  config.vm.hostname = "vagrant-jenkins.local"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
  end

  config.vm.network :forwarded_port, guest: 8080, host: 8080

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y puppet-common
  SHELL

  config.vm.provision :puppet do |puppet|
    puppet.manifest_file = "prepare_environment.pp"
  end

  config.vm.provision :puppet do |puppet|
    puppet.manifest_file = "jenkins.pp"
  end 
end
