# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
  end

  config.vm.network :forwarded_port, guest: 8080, host: 8080

  config.vm.provision :puppet do |puppet|
    puppet.manifest_file = "prepare_environment.pp"
  end

  config.vm.provision :puppet do |puppet|
    puppet.manifest_file = "jenkins.pp"
  end 
end
