# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "puppetlabs/ubuntu-14.04-64-nocm"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
  end
 
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y puppet-common
  SHELL

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    # contains: "package { 'apache2': ensure => 'installed', }"
    puppet.manifest_file = "default.pp"
  end 
end
